#
# Native source inventory for the CMake build.
# This file intentionally avoids file(GLOB...) so source changes are explicit.
#

set(GECODE_SUPPORT_SOURCES
  gecode/support/allocator.cpp
  gecode/support/exception.cpp
  gecode/support/heap.cpp
  gecode/support/hw-rnd.cpp
  gecode/support/thread/thread.cpp
)

set(GECODE_KERNEL_SOURCES
  gecode/kernel/archive.cpp
  gecode/kernel/branch/action.cpp
  gecode/kernel/branch/afc.cpp
  gecode/kernel/branch/chb.cpp
  gecode/kernel/branch/function.cpp
  gecode/kernel/core.cpp
  gecode/kernel/data/array.cpp
  gecode/kernel/data/rnd.cpp
  gecode/kernel/exception.cpp
  gecode/kernel/gpi.cpp
  gecode/kernel/memory/manager.cpp
  gecode/kernel/memory/region.cpp
  gecode/kernel/trace/filter.cpp
  gecode/kernel/trace/general.cpp
  gecode/kernel/trace/recorder.cpp
  gecode/kernel/trace/tracer.cpp
)

set(GECODE_SEARCH_SOURCES
  gecode/search/bab.cpp
  gecode/search/cpprofiler/tracer.cpp
  gecode/search/cutoff.cpp
  gecode/search/dfs.cpp
  gecode/search/engine.cpp
  gecode/search/exception.cpp
  gecode/search/lds.cpp
  gecode/search/nogoods.cpp
  gecode/search/options.cpp
  gecode/search/par/pbs.cpp
  gecode/search/pbs.cpp
  gecode/search/rbs.cpp
  gecode/search/seq/dead.cpp
  gecode/search/seq/pbs.cpp
  gecode/search/seq/rbs.cpp
  gecode/search/stop.cpp
  gecode/search/tracer.cpp
)

set(GECODE_INT_SOURCES
  gecode/int/arithmetic.cpp
  gecode/int/arithmetic/mult.cpp
  gecode/int/array.cpp
  gecode/int/bin-packing.cpp
  gecode/int/bin-packing/conflict-graph.cpp
  gecode/int/bin-packing/propagate.cpp
  gecode/int/bool.cpp
  gecode/int/bool/eqv.cpp
  gecode/int/branch.cpp
  gecode/int/branch/action.cpp
  gecode/int/branch/chb.cpp
  gecode/int/branch/val-sel-commit.cpp
  gecode/int/branch/view-sel.cpp
  gecode/int/branch/view-values.cpp
  gecode/int/channel.cpp
  gecode/int/channel/link-multi.cpp
  gecode/int/channel/link-single.cpp
  gecode/int/circuit.cpp
  gecode/int/count.cpp
  gecode/int/cumulative.cpp
  gecode/int/cumulatives.cpp
  gecode/int/distinct.cpp
  gecode/int/distinct/cbs.cpp
  gecode/int/distinct/eqite.cpp
  gecode/int/dom.cpp
  gecode/int/element.cpp
  gecode/int/element/pair.cpp
  gecode/int/exception.cpp
  gecode/int/exec.cpp
  gecode/int/exec/when.cpp
  gecode/int/extensional-regular.cpp
  gecode/int/extensional-tuple-set.cpp
  gecode/int/extensional/dfa.cpp
  gecode/int/extensional/tuple-set.cpp
  gecode/int/gcc.cpp
  gecode/int/int-set.cpp
  gecode/int/ldsb.cpp
  gecode/int/ldsb/sym-imp.cpp
  gecode/int/ldsb/sym-obj.cpp
  gecode/int/linear-bool.cpp
  gecode/int/linear-int.cpp
  gecode/int/linear/bool-post.cpp
  gecode/int/linear/int-post.cpp
  gecode/int/member.cpp
  gecode/int/no-overlap.cpp
  gecode/int/nvalues.cpp
  gecode/int/order.cpp
  gecode/int/order/propagate.cpp
  gecode/int/precede.cpp
  gecode/int/rel.cpp
  gecode/int/relax.cpp
  gecode/int/sequence.cpp
  gecode/int/sorted.cpp
  gecode/int/trace.cpp
  gecode/int/trace/tracer.cpp
  gecode/int/unary.cpp
  gecode/int/unshare.cpp
  gecode/int/var-imp/bool.cpp
  gecode/int/var-imp/int.cpp
  gecode/int/var/bool.cpp
  gecode/int/var/int.cpp
)

set(GECODE_SET_SOURCES
  gecode/set/array.cpp
  gecode/set/bool.cpp
  gecode/set/branch.cpp
  gecode/set/branch/action.cpp
  gecode/set/branch/chb.cpp
  gecode/set/branch/ngl.cpp
  gecode/set/branch/val-sel-commit.cpp
  gecode/set/branch/view-sel.cpp
  gecode/set/cardinality.cpp
  gecode/set/channel.cpp
  gecode/set/convex.cpp
  gecode/set/convex/conv.cpp
  gecode/set/convex/hull.cpp
  gecode/set/distinct.cpp
  gecode/set/distinct/atmostOne.cpp
  gecode/set/dom.cpp
  gecode/set/element.cpp
  gecode/set/exception.cpp
  gecode/set/exec.cpp
  gecode/set/int.cpp
  gecode/set/ldsb.cpp
  gecode/set/ldsb/sym-imp.cpp
  gecode/set/precede.cpp
  gecode/set/rel-op-const-cvc.cpp
  gecode/set/rel-op-const-cvv.cpp
  gecode/set/rel-op-const-vcc.cpp
  gecode/set/rel-op-const-vcv.cpp
  gecode/set/rel-op-const-vvc.cpp
  gecode/set/rel-op-singleton.cpp
  gecode/set/rel-op-ternary.cpp
  gecode/set/rel-op.cpp
  gecode/set/rel-op/post-compl-cvc.cpp
  gecode/set/rel-op/post-compl-cvv.cpp
  gecode/set/rel-op/post-compl-vvc.cpp
  gecode/set/rel-op/post-compl.cpp
  gecode/set/rel-op/post-nocompl-cvc.cpp
  gecode/set/rel-op/post-nocompl-cvv.cpp
  gecode/set/rel-op/post-nocompl-vvc.cpp
  gecode/set/rel-op/post-nocompl.cpp
  gecode/set/rel.cpp
  gecode/set/relax.cpp
  gecode/set/sequence.cpp
  gecode/set/sequence/seq-u.cpp
  gecode/set/sequence/seq.cpp
  gecode/set/trace.cpp
  gecode/set/trace/tracer.cpp
  gecode/set/var-imp/integerset.cpp
  gecode/set/var-imp/set.cpp
  gecode/set/var/set.cpp
)

set(GECODE_FLOAT_SOURCES
  gecode/float/arithmetic.cpp
  gecode/float/array.cpp
  gecode/float/bool.cpp
  gecode/float/branch.cpp
  gecode/float/branch/action.cpp
  gecode/float/branch/chb.cpp
  gecode/float/branch/val-sel-commit.cpp
  gecode/float/branch/view-sel.cpp
  gecode/float/channel.cpp
  gecode/float/dom.cpp
  gecode/float/exception.cpp
  gecode/float/exec.cpp
  gecode/float/linear.cpp
  gecode/float/linear/post.cpp
  gecode/float/rel.cpp
  gecode/float/relax.cpp
  gecode/float/rounding.cpp
  gecode/float/trace.cpp
  gecode/float/trace/tracer.cpp
  gecode/float/transcendental.cpp
  gecode/float/trigonometric.cpp
  gecode/float/var-imp/float.cpp
  gecode/float/var/float.cpp
)

set(GECODE_MINIMODEL_SOURCES
  gecode/minimodel/bool-expr.cpp
  gecode/minimodel/dom.cpp
  gecode/minimodel/exception.cpp
  gecode/minimodel/float-arith.cpp
  gecode/minimodel/float-expr.cpp
  gecode/minimodel/float-rel.cpp
  gecode/minimodel/int-arith.cpp
  gecode/minimodel/int-expr.cpp
  gecode/minimodel/int-rel.cpp
  gecode/minimodel/ipl.cpp
  gecode/minimodel/optimize.cpp
  gecode/minimodel/reg.cpp
  gecode/minimodel/set-expr.cpp
  gecode/minimodel/set-rel.cpp
)

set(GECODE_DRIVER_SOURCES
  gecode/driver/options.cpp
  gecode/driver/script.cpp
)

set(GECODE_GIST_SOURCES
  gecode/gist/drawingcursor.cpp
  gecode/gist/gecodelogo.cpp
  gecode/gist/gist.cpp
  gecode/gist/mainwindow.cpp
  gecode/gist/node.cpp
  gecode/gist/nodestats.cpp
  gecode/gist/nodewidget.cpp
  gecode/gist/preferences.cpp
  gecode/gist/qtgist.cpp
  gecode/gist/spacenode.cpp
  gecode/gist/stopbrancher.cpp
  gecode/gist/textoutput.cpp
  gecode/gist/treecanvas.cpp
  gecode/gist/visualnode.cpp
)

set(GECODE_FLATZINC_SOURCES
  gecode/flatzinc/blackbox-backend.cpp
  gecode/flatzinc/blackbox-propagator.cpp
  gecode/flatzinc/branch.cpp
  gecode/flatzinc/flatzinc.cpp
  gecode/flatzinc/lexer.yy.cpp
  gecode/flatzinc/parser.tab.cpp
  gecode/flatzinc/registry.cpp
)

set(GECODE_TEST_SOURCES
  test/afc.cpp
  test/array.cpp
  test/assign.cpp
  test/assign/bool.cpp
  test/assign/float.cpp
  test/assign/int.cpp
  test/assign/set.cpp
  test/branch.cpp
  test/branch/bool.cpp
  test/branch/float.cpp
  test/branch/int.cpp
  test/branch/set.cpp
  test/flatzinc.cpp
  test/flatzinc/2dpacking.cpp
  test/flatzinc/alpha.cpp
  test/flatzinc/battleships1.cpp
  test/flatzinc/battleships10.cpp
  test/flatzinc/battleships2.cpp
  test/flatzinc/battleships3.cpp
  test/flatzinc/battleships4.cpp
  test/flatzinc/battleships5.cpp
  test/flatzinc/battleships7.cpp
  test/flatzinc/battleships9.cpp
  test/flatzinc/blackbox.cpp
  test/flatzinc/blocksworld_instance_1.cpp
  test/flatzinc/blocksworld_instance_2.cpp
  test/flatzinc/bool_clause.cpp
  test/flatzinc/bug232.cpp
  test/flatzinc/bug319.cpp
  test/flatzinc/bugfix_r6746.cpp
  test/flatzinc/bugfix_r7854.cpp
  test/flatzinc/cumulatives.cpp
  test/flatzinc/cumulatives_full_1.cpp
  test/flatzinc/cumulatives_full_2.cpp
  test/flatzinc/cumulatives_full_3.cpp
  test/flatzinc/cumulatives_full_4.cpp
  test/flatzinc/cumulatives_full_5.cpp
  test/flatzinc/cumulatives_full_6.cpp
  test/flatzinc/cumulatives_full_7.cpp
  test/flatzinc/cumulatives_full_8.cpp
  test/flatzinc/cutstock.cpp
  test/flatzinc/empty_domain_1.cpp
  test/flatzinc/empty_domain_2.cpp
  test/flatzinc/eq20.cpp
  test/flatzinc/factory_planning_instance.cpp
  test/flatzinc/golomb.cpp
  test/flatzinc/int_set_as_type1.cpp
  test/flatzinc/int_set_as_type2.cpp
  test/flatzinc/jobshop.cpp
  test/flatzinc/jobshop2x2.cpp
  test/flatzinc/knights.cpp
  test/flatzinc/langford2.cpp
  test/flatzinc/latin_squares_fd.cpp
  test/flatzinc/magicsq_3.cpp
  test/flatzinc/magicsq_4.cpp
  test/flatzinc/magicsq_5.cpp
  test/flatzinc/multidim_knapsack_simple.cpp
  test/flatzinc/no_warn_empty_domain.cpp
  test/flatzinc/on_restart_complete.cpp
  test/flatzinc/on_restart_last_val_bool.cpp
  test/flatzinc/on_restart_last_val_float.cpp
  test/flatzinc/on_restart_last_val_int.cpp
  test/flatzinc/on_restart_last_val_set.cpp
  test/flatzinc/on_restart_sol_bool.cpp
  test/flatzinc/on_restart_sol_float.cpp
  test/flatzinc/on_restart_sol_int.cpp
  test/flatzinc/on_restart_sol_set.cpp
  test/flatzinc/oss.cpp
  test/flatzinc/output_test.cpp
  test/flatzinc/packing.cpp
  test/flatzinc/perfsq.cpp
  test/flatzinc/perfsq2.cpp
  test/flatzinc/photo.cpp
  test/flatzinc/product_fd.cpp
  test/flatzinc/product_lp.cpp
  test/flatzinc/quasigroup_qg5.cpp
  test/flatzinc/queen_cp2.cpp
  test/flatzinc/queen_ip.cpp
  test/flatzinc/queens4.cpp
  test/flatzinc/radiation.cpp
  test/flatzinc/sat_arith1.cpp
  test/flatzinc/sat_array_bool_and.cpp
  test/flatzinc/sat_array_bool_or.cpp
  test/flatzinc/sat_cmp_reif.cpp
  test/flatzinc/sat_eq_reif.cpp
  test/flatzinc/shared_array_element.cpp
  test/flatzinc/simple_sat.cpp
  test/flatzinc/singHoist2.cpp
  test/flatzinc/steiner_triples.cpp
  test/flatzinc/subtyping.cpp
  test/flatzinc/sudoku.cpp
  test/flatzinc/template_design.cpp
  test/flatzinc/tenpenki_1.cpp
  test/flatzinc/tenpenki_2.cpp
  test/flatzinc/tenpenki_3.cpp
  test/flatzinc/tenpenki_4.cpp
  test/flatzinc/tenpenki_5.cpp
  test/flatzinc/tenpenki_6.cpp
  test/flatzinc/test_approx_bnb.cpp
  test/flatzinc/test_array_just_right.cpp
  test/flatzinc/test_assigned_var_bounds_bad.cpp
  test/flatzinc/test_flatzinc_output_anns.cpp
  test/flatzinc/test_fzn_arith.cpp
  test/flatzinc/test_fzn_arrays.cpp
  test/flatzinc/test_fzn_coercions.cpp
  test/flatzinc/test_fzn_comparison.cpp
  test/flatzinc/test_fzn_logic.cpp
  test/flatzinc/test_fzn_sets.cpp
  test/flatzinc/test_int_div.cpp
  test/flatzinc/test_int_mod.cpp
  test/flatzinc/test_int_ranges_as_values.cpp
  test/flatzinc/test_seq_search.cpp
  test/flatzinc/timetabling.cpp
  test/flatzinc/trucking.cpp
  test/flatzinc/warehouses.cpp
  test/flatzinc/warehouses_small.cpp
  test/flatzinc/wolf_goat_cabbage.cpp
  test/flatzinc/zebra.cpp
  test/float.cpp
  test/float/arithmetic.cpp
  test/float/basic.cpp
  test/float/channel.cpp
  test/float/dom.cpp
  test/float/linear.cpp
  test/float/mm-lin.cpp
  test/float/rel.cpp
  test/float/transcendental.cpp
  test/float/trigonometric.cpp
  test/groups.cpp
  test/int.cpp
  test/int/arithmetic.cpp
  test/int/basic.cpp
  test/int/bin-packing.cpp
  test/int/bool.cpp
  test/int/channel.cpp
  test/int/circuit.cpp
  test/int/count.cpp
  test/int/cumulative.cpp
  test/int/cumulatives.cpp
  test/int/distinct.cpp
  test/int/dom.cpp
  test/int/element.cpp
  test/int/exec.cpp
  test/int/extensional.cpp
  test/int/gcc.cpp
  test/int/linear.cpp
  test/int/member.cpp
  test/int/mm-arithmetic.cpp
  test/int/mm-bool.cpp
  test/int/mm-count.cpp
  test/int/mm-lin.cpp
  test/int/mm-rel.cpp
  test/int/no-overlap.cpp
  test/int/nvalues.cpp
  test/int/order.cpp
  test/int/precede.cpp
  test/int/rel.cpp
  test/int/sequence.cpp
  test/int/sorted.cpp
  test/int/unary.cpp
  test/int/unshare.cpp
  test/ldsb.cpp
  test/nogoods.cpp
  test/region.cpp
  test/search.cpp
  test/set.cpp
  test/set/channel.cpp
  test/set/construct.cpp
  test/set/convex.cpp
  test/set/distinct.cpp
  test/set/dom.cpp
  test/set/element.cpp
  test/set/exec.cpp
  test/set/int.cpp
  test/set/mm-set.cpp
  test/set/precede.cpp
  test/set/rel-op-const.cpp
  test/set/rel-op.cpp
  test/set/rel.cpp
  test/set/sequence.cpp
  test/test.cpp
)

set(GECODE_TEST_BLACKBOX_EXEC_SOURCE test/flatzinc/blackbox-exec.cpp)
set(GECODE_TEST_BLACKBOX_DLL_SOURCE test/flatzinc/blackbox-dll.cpp)

set(GECODE_FLATZINC_EXE_SOURCE tools/flatzinc/fzn-gecode.cpp)
